<h1>Privacy policy</h1>
<p class="meta">Effective from 28 September 2026</p>

<p>This policy describes what personal data the FlatShare mobile app (iOS, Android) and its server process, for what purpose and how long, and what rights you have. Processing is carried out under the EU General Data Protection Regulation (GDPR, Regulation (EU) 2016/679) and Hungarian Act CXII of 2011. In case of a discrepancy, the <a href="{{ route('privacy', ['lang' => 'hu']) }}">Hungarian version</a> prevails.</p>

<h2>1. Data controller</h2>
<div class="card">
    <p style="margin: 0"><strong>Áron Papp</strong> (private individual)<br>
    Postal address: [POSTAL ADDRESS]<br>
    E-mail: <a href="mailto:{{ $email }}">{{ $email }}</a></p>
</div>
<p>You can reach us at this address with any privacy question or request.</p>

<h2>2. What data we process</h2>

<h3>2.1. Account data</h3>
<p>We do not ask for a password: you sign in with your Google or Apple account. Authentication is handled by WorkOS, except Sign in with Apple on iPhone, which Apple handles directly with our server. On sign-in we receive and store:</p>
<ul>
    <li>first and last name,</li>
    <li>e-mail address (with Apple this may be a private relay address generated by Apple),</li>
    <li>the web address of your profile picture (we do not copy the image, it loads from Google's/Apple's servers),</li>
    <li>your internal WorkOS user ID, or with Sign in with Apple on iPhone your Apple user ID and an Apple sign-in token (stored encrypted, only so we can revoke your Apple sign-in when you delete the account),</li>
    <li>your language setting (Hungarian/English).</li>
</ul>
<p>We also store the nickname you set.</p>

<h3>2.2. Household data</h3>
<p>The app exists to organise a shared household, so we store:</p>
<ul>
    <li>households (name, join code, settings such as the weekly or monthly scoring period), your membership and role (admin, member, child);</li>
    <li>chores (name, category, difficulty, duration, recurrence, assignment mode) and their occurrences: who claimed them, who completed them and when;</li>
    <li>your points, point transactions, weekly/monthly goals and any penalty points;</li>
    <li>the personal weight you gave to chores (how much you like them) and the rotation order;</li>
    <li>chore swaps (offers, acceptances) and grace days you requested;</li>
    <li>rewards (name, description, point value) and their redemptions;</li>
    <li>the stickers in your sticker album;</li>
    <li>records of members leaving (so admins can decide about the chores of a former member);</li>
    <li>a change log of household data (what changed, when and by whom).</li>
</ul>

<h3>2.3. Notifications and calendar</h3>
<ul>
    <li><strong>Push notification token</strong> and device platform (iOS/Android) – only if you allow notifications. It is deleted when you sign out.</li>
    <li><strong>Calendar subscription</strong>: if you turn it on, we create a link containing a secret random identifier that lets your calendar app fetch the household's chores (chore names, due dates, assignees' names). Anyone with the link can see this data, so do not share it; you can request a new link in the app at any time, which invalidates the old one.</li>
</ul>

<h3>2.4. Technical data</h3>
<ul>
    <li>The access token of your signed-in session (stored on the server only as a hash) and its last use.</li>
    <li>Server logs: IP address, time and path of requests, error messages – for security and to fix bugs.</li>
</ul>

<h3>2.5. Data stored on your phone</h3>
<ul>
    <li>Your sign-in token is kept in the device's secure storage (iOS Keychain / Android Keystore).</li>
    <li>The selected household and your appearance settings (theme, palette, font, icon set) are stored on the device only.</li>
    <li>The <strong>camera</strong> is used only to scan a household's QR code. The image is processed on the device and is neither stored nor transmitted.</li>
</ul>

<h3>2.6. What we do not collect</h3>
<p>We do not collect location, contacts, photos, health or financial data. We use no advertising, advertising identifiers, third-party analytics or tracking, and we never sell your data.</p>

<h2>3. Who can see your data</h2>
<p>The other members of your household(s) can see your name (or nickname), profile picture, e-mail address, points, the chores you claimed and completed, your rewards and redemptions. Members of other households cannot see your data.</p>

<h2>4. Purposes and legal bases</h2>
<div class="table-wrap">
    <table>
        <thead><tr><th>Purpose</th><th>Data</th><th>Legal basis</th></tr></thead>
        <tbody>
            <tr><td>Creating the account, signing in</td><td>account data, access token</td><td>performance of a contract – Art. 6(1)(b) GDPR</td></tr>
            <tr><td>Organising the household (chores, points, rewards, statistics)</td><td>data in section 2.2</td><td>performance of a contract – Art. 6(1)(b) GDPR</td></tr>
            <tr><td>Sending push notifications</td><td>push token, platform, language</td><td>consent – Art. 6(1)(a) GDPR; withdraw any time in your phone's settings</td></tr>
            <tr><td>Calendar subscription</td><td>calendar token, chores</td><td>performance of a contract – Art. 6(1)(b) GDPR; only if you turn it on</td></tr>
            <tr><td>Change log, server logs: detecting abuse and errors, security</td><td>change log, IP address, technical data</td><td>legitimate interest – Art. 6(1)(f) GDPR</td></tr>
        </tbody>
    </table>
</div>

<h2>5. Processors and transfers</h2>
<p>We use the following providers, who process data only on our instructions to provide the service:</p>
<div class="table-wrap">
    <table>
        <thead><tr><th>Provider</th><th>Role</th><th>Data involved</th></tr></thead>
        <tbody>
            <tr><td>WorkOS, Inc. (USA)</td><td>sign-in, authentication</td><td>name, e-mail, profile picture, ID</td></tr>
            <tr><td>Google LLC / Apple Inc.</td><td>provider of the sign-in method you choose</td><td>account data they hold, under their own privacy terms</td></tr>
            <tr><td>650 Industries, Inc. (Expo, USA)</td><td>relaying push notifications</td><td>push token, notification text</td></tr>
            <tr><td>Apple Push Notification service, Google Firebase Cloud Messaging</td><td>delivering notifications to the device</td><td>push token, notification text</td></tr>
            <tr><td>[HOSTING PROVIDER NAME, SEAT]</td><td>running the server and database</td><td>all data stored on the server</td></tr>
        </tbody>
    </table>
</div>
<p>Transfers outside the European Economic Area (USA) rely on the European Commission's adequacy decision (EU–US Data Privacy Framework) or the Standard Contractual Clauses adopted by the European Commission.</p>

<h2>6. How long we keep data</h2>
<ul>
    <li>Account and household data: until you delete your account.</li>
    <li>Push token: until you sign out, or as long as the notification service reports it as valid.</li>
    <li>Change log: up to 365 days, then deleted automatically.</li>
    <li>Server logs: up to 14 days; backups: up to 30 days.</li>
    <li>If you leave a household, the history of your work there (completions, point transactions) is kept so the other members' scores stay accurate.</li>
</ul>

<h2>7. Deleting your account</h2>
<p>You can delete your account in the app at any time: <strong>Profile picture → Settings → Delete account</strong>. If you cannot access the app, you can request it by e-mail. On deletion:</p>
<ul>
    <li>your name, nickname, e-mail address and profile picture are irreversibly removed (the account is anonymized),</li>
    <li>your access and push tokens, personal settings and your WorkOS account are deleted, and your Sign in with Apple authorization is revoked at Apple,</li>
    <li>households you created are deleted for all their members,</li>
    <li>you leave households created by others; the shared history there is attributed to an anonymous "Deleted user" that cannot be linked to you.</li>
</ul>
<p>Details: <a href="{{ route('account-deletion', ['lang' => 'en']) }}">Delete your account and data</a>.</p>

<h2>8. Your rights</h2>
<p>Under the GDPR you have the right to:</p>
<ul>
    <li><strong>access</strong> – ask what data we hold about you and get a copy;</li>
    <li><strong>rectification</strong> – change your nickname and language in the app, your name and e-mail in your Google/Apple account;</li>
    <li><strong>erasure</strong> – see section 7;</li>
    <li><strong>restriction</strong> and to <strong>object</strong> to processing based on legitimate interest;</li>
    <li><strong>data portability</strong> – on request we provide the data you gave us in a machine-readable format;</li>
    <li><strong>withdraw consent</strong> – turn off push notifications in your phone's settings at any time.</li>
</ul>
<p>Send requests to the e-mail address above; we reply within one month. If you believe the processing infringes your rights, you can lodge a complaint with the Hungarian National Authority for Data Protection and Freedom of Information (NAIH, Falk Miksa utca 9–11, 1055 Budapest, <a href="https://naih.hu">naih.hu</a>), with the supervisory authority of your country of residence, or go to court.</p>

<h2>9. Children</h2>
<p>A "child" role exists within households, but creating an account requires an own Google or Apple account. Children under 16 may only use the app with the consent and supervision of a parent or legal guardian. A parent can request the deletion of a child's data at the e-mail address above.</p>

<h2>10. Security</h2>
<p>All data between the app and the server travels over an encrypted (HTTPS/TLS) connection. Access tokens are stored only as hashes, household data is accessible only to its members, and the server only serves requests from the official FlatShare app.</p>

<h2>11. Changes</h2>
<p>If this policy changes materially, we will let you know in the app and on this page. The current version is always available at this address.</p>
